### 
POST http://localhost:4003/auth/sign-in
Content-Type: application/json

{
    "email":"ajmir@gmail.com",
    "password":"123456"
}
### 
POST http://localhost:4003/auth/sign-up
Content-Type: application/json

{
    "email":"ajmir@gmail.com",
    "password":"123456"
}
###
GET http://localhost:4003/data